# -*- coding: utf-8 -*-
"""02_PyTorch_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1icCMCDbiqDHgGm9MzmkmXc6f5gy1Zulg
"""

# 02. Neural network classifications with PyTroch

"""## 1. Make Classified Data and get it ready"""

import sklearn
from sklearn.datasets import make_circles
import numpy as np

# mkae a 1000 samples
n_samples = 1000

# creat cirsles
x, y = make_circles(n_samples,
                    noise = 0.03,
                    random_state=42)

len(x), len(y)

print(x[:5], y[:5])

# Make DataFrame of circle data
import pandas as pd
circles = pd.DataFrame({'x1': x[:, 0],
                        'x2': x[:, 1],
                        "label" : y})
circles.head(5)

# visualize
import matplotlib.pyplot as plt
plt.scatter(x=x[:, 0],
            y=x[:, 1],
            c=y,
            cmap=plt.cm.RdYlBu);

"""Note: The dta we are wroking with is often refered to Toy dataset, a data set that is small enough to experiment but still sizeable enough to practice the fundamentals.

### 1.1   Check input and output shapes
"""

x.shape, y.shape

# view the first examples
x_samples = x[0]
y_samples = y[0]
print(f"Values for one sample of x: {x_samples}")
print(f"Values for one sample of y: {y_samples}")
print(f"shapes for one sample of x: {x_samples.shape}")
print(f"shapes for one sample of y: {y_samples.shape}")

"""### 1.2 Trun data into Tensor"""

import torch
torch.__version__

type(x), x.dtype

if not torch.is_tensor(x):
    x = torch.from_numpy(x).type(torch.float)
    y = torch.from_numpy(y).type(torch.float)

x[:5], y[:5]

type(x), x.dtype, y.dtype

# split data into training and test dats sets

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,
                                                    y,
                                                    test_size = 0.2, #0.2 = 205 of the datad for the test
                                                    random_state=42)

len(x_train), len(y_train), len(x_test), len(y_test)

n_samples

"""from pandas.core import algorithms
## 2. Building a model

Lets build a model to classify our blue and red dots.

to do so, we want to:
1. setup device agonistic code.
2. construct a model(by subclassing `nn.Module`)
3. Define a loss function and optimizer
4. creat a trainig and test loop
"""

import torch
from torch import nn
device = "cuda" if torch.cuda.is_available() else "cpu"
device

"""1. subclass `nn.Model`
2. Create 2`nn.linear()` layers that are capable of handeling the shapes of our data
3. Defines a `forward()` method
4. Instatiate an instnce of our model class and send it to the traget `device`
"""

# 1. Construct a model
class circlemodel(nn.Module):
  def __init__(self):
    super().__init__()
    # 2. Create 2 nn.linear layers
    self.layer_1 = nn.Linear(in_features=2, out_features=5) # takes 2 gives 5
    self.layer_2 = nn.Linear(in_features=5, out_features=1) # takes given 5 and gives 1 back
# 3. forward pass
def forward(self, x):
  return self.layer_2(self.layer_1(x)) # x --> layer_1 --> layer_2
# 4. Instantitate an instance of our model class and send it to the target model
model_0 = circlemodel().to(device)
model_0

device

next(model_0.parameters()).device

